version: "3"
services:

  jupyter:
    image: jupyterlab:latest
    ports:
      - 8888:8888
    depends_on:
      - database

  database:
    image: postgreslab:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

