version: "3"
services:

  jupyter:
    image: jupyterlab:latest
    ports:
      - 8888:8888
    depends_on:
      - postgres_db

  postgres_db:
    image: postgreslab:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: mongo
        MONGO_INITDB_ROOT_PASSWORD: mongo

